name: Refresh data
#on: [push]
on: 
  workflow_dispatch:
  schedule:
    - cron:  '45 19 * * *' # UTC -> No timezone support!!
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true #to use in build & deploy step.
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://api.esios.ree.es/indicators/1001
          CONFIGURATION: '{ "method": "GET", "headers": {"Accept": "application/json; application/vnd.esios-api-v1+json", "Content-Type": "application/json", "Host": "api.esios.ree.es", "Cookie":"", "Authorization": "Token token=\"${{ secrets.API_TOKEN }}\"" } }'
          SAVE_NAME: ${{ steps.date.outputs.date }} #YYYY-MM-DD from 2nd step
          
      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main # Pushes the updates to the main branch.
          FOLDER: fetch-api-data-action # The location of the json file saved by the Fetch API Data action.
          TARGET_FOLDER: data # Saves the data into the 'data' directory on the branch.
