name: Scheduled - Get JSON
on:
  push:
  #workflow_dispatch:
  #schedule:
  #  - cron:  '45 20 * * */1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Data
      run: |
        curl "https://api.esios.ree.es/indicators/1001" -H "Content-Type: application/json" -H "Accept: application/json; application/vnd.esios-api-v1+json" -H "Content-Type: application/json" -H "Host: api.esios.ree.es" -H "Cookie:" -H "Authorization: Token token='${{ secrets.API_TOKEN }}'" -o data.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git diff --quiet || (git add -A && git commit -m "Updated with latest data")
        git push
