name: Get JSON
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://opendata.aragon.es/GA_OD_Core/download?resource_id=2181&formato=json
          CONFIGURATION: '{ "method": "GET", "headers": {"Accept": "application/json", "Content-Type": "application/json", "Host": "opendata.aragon.es"} }'
          SAVE_LOCATION: public
          SAVE_NAME: data
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: public/data.json
          commit-msg: Updated data 
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
