name: Refresh data
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://api.esios.ree.es/indicators/1001
          CONFIGURATION: '{ "method": "GET", "headers": {"Accept": "application/json; application/vnd.esios-api-v1+json", "Content-Type": "application/json", "Host": "api.esios.ree.es", "Cookie":"", "Authorization": "Token token=\"${{ secrets.API_TOKEN }}\"" } }'
